### ISSUE TITLE
-v and Python 2.7.2 (?)

### ISSUE THREAD

**Issue by jblaine** [disqus/porkchop#1]
Runs fine without -v

<pre>
porkchop:beijing> ~/bin/porkchop -v
Traceback (most recent call last):
  File "/afs/rcf/user/jblaine/bin/porkchop", line 8, in <module>
    load_entry_point('porkchop==0.6', 'console_scripts', 'porkchop')()
  File "/afs/rcf/user/jblaine/lib/python2.7/site-packages/porkchop-0.6-py2.7.egg/porkchop/commandline.py", line 56, in main
    logger = get_logger(logging.DEBUG)
  File "/afs/rcf/user/jblaine/lib/python2.7/site-packages/porkchop-0.6-py2.7.egg/porkchop/commandline.py", line 14, in get_logger
    logger = logging.getLogger(name)
  File "/usr/rcf-tools/python-2.7.2/lib/python2.7/logging/__init__.py", line 1538, in getLogger
    return Logger.manager.getLogger(name)
  File "/usr/rcf-tools/python-2.7.2/lib/python2.7/logging/__init__.py", line 1021, in getLogger
    self._fixupParents(rv)
  File "/usr/rcf-tools/python-2.7.2/lib/python2.7/logging/__init__.py", line 1042, in _fixupParents
    i = name.rfind(".")
AttributeError: 'int' object has no attribute 'rfind'
porkchop:beijing>
</pre>

**Comment by ohlol** [comment]
Ah, yeah, I think I added that meaning to give the option to increase verbosity but didn't actually implement it. I'll take it out for now.

**Comment by ohlol** [comment]
I removed this in 91bca56eeb4703c354fe952733b04cdd28b20e74
